[2023-06-09T14:53:18.331+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T14:53:18.336+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09T14:53:18.337+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-09T14:53:18.361+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-06-08 00:00:00+00:00
[2023-06-09T14:53:18.372+0000] {standard_task_runner.py:57} INFO - Started process 1871 to run task
[2023-06-09T14:53:18.379+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpn479rnnr']
[2023-06-09T14:53:18.383+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask insert_into_table
[2023-06-09T14:53:18.426+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2023-06-08T00:00:00+00:00 [running]> on host 94560a00d375
[2023-06-09T14:53:18.484+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='znawawi' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-08T00:00:00+00:00'
[2023-06-09T14:53:18.485+0000] {sql.py:262} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-06-08', 'dag_with_postgres_operator_v04')
        
[2023-06-09T14:53:18.492+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-09T14:53:18.528+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-09T14:53:18.535+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-06-08', 'dag_with_postgres_operator_v04')
        , parameters: None
[2023-06-09T14:53:18.538+0000] {sql.py:384} INFO - Rows affected: 1
[2023-06-09T14:53:18.547+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, execution_date=20230608T000000, start_date=20230609T145318, end_date=20230609T145318
[2023-06-09T14:53:18.588+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-09T14:53:18.603+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
